# Generated by Django 5.2.10 on 2026-02-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="stripe_payment_status",
            field=models.CharField(
                default="pending", max_length=50, verbose_name="Статус оплаты Stripe"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_payment_url",
            field=models.URLField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Ссылка на оплату Stripe",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_price_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ID цены Stripe"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_product_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ID продукта Stripe"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_session_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ID сессии Stripe"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Наличные"),
                    ("transfer", "Перевод на счет"),
                    ("stripe", "Stripe"),
                ],
                max_length=10,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
