# Generated by Django 5.2.10 on 2026-02-05 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import materials.validators


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_course_owner_lesson_owner_alter_course_preview_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
        migrations.AlterField(
            model_name="lesson",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video_link",
            field=models.URLField(
                validators=[materials.validators.validate_youtube_only],
                verbose_name="Ссылка на видео",
            ),
        ),
    ]
